#!/usr/bin/env python3
"""Run the PTB-XL EDA headlessly: write figures, prevalence tables, and a summary.

Outputs land in ``docs/eda/`` (figures + CSVs + summary.md) so they can be committed
and reviewed without re-running a notebook.
"""

from __future__ import annotations

import matplotlib

matplotlib.use("Agg")  # headless: render figures to PNG without a display

from src.config import ROOT
from src.data import eda, labels as L

OUT = ROOT / "docs" / "eda"
FIG = OUT / "figures"


def main() -> int:
    df = L.load_database()
    scp = L.load_scp_statements()

    prev = eda.code_prevalence(df, scp)
    sc = eda.superclass_prevalence(df, scp)
    lpr = eda.labels_per_record(df)
    rpp = eda.records_per_patient(df)
    demo = eda.demographics_summary(df)
    miss = eda.missingness(df)

    OUT.mkdir(parents=True, exist_ok=True)
    prev.to_csv(OUT / "code_prevalence.csv", index=False)
    sc.to_csv(OUT / "superclass_prevalence.csv", index=False)

    eda.plot_code_prevalence(prev, FIG / "code_prevalence.png")
    eda.plot_superclass(sc, FIG / "superclass_distribution.png")
    eda.plot_demographics(df, FIG / "demographics.png")
    eda.plot_labels_per_record(lpr, FIG / "labels_per_record.png")

    lines = [
        "# PTB-XL EDA summary",
        "",
        "_Auto-generated by `scripts/run_eda.py`. Metadata only (no signal files needed)._",
        "",
        "## Dataset shape",
        f"- Records: **{demo['n_records']:,}**  |  Patients: **{demo['n_patients']:,}**",
        f"- SCP statements (label space): **{len(L.build_label_space())}**",
        f"- Median age: **{demo['age_median']:.0f}** (mean {demo['age_mean']}), "
        f"missing age: {demo['age_missing']}",
        f"- Age anonymization: **{demo['age_anonymized_300']}** records have age=300 "
        f"(PTB-XL convention for patients >89); excluded from age stats/plot above",
        f"- Sex: **{demo['sex_male']:,}** male / **{demo['sex_female']:,}** female",
        f"- Devices: {demo['n_devices']}  |  Sites: {demo['n_sites']}",
        f"- Records per patient: max **{int(rpp.max())}**, "
        f"{int((rpp > 1).sum()):,} patients have >1 recording "
        f"(patient-level splitting is required to avoid leakage)",
        "",
        "## Class imbalance",
        f"- Most common statement: **{prev.iloc[0]['code']}** "
        f"({prev.iloc[0]['count']:,} records, {prev.iloc[0]['prevalence_%']}%)",
        f"- Rarest statement: **{prev.iloc[-1]['code']}** "
        f"({prev.iloc[-1]['count']:,} records)",
        f"- Statements appearing in <100 records: "
        f"**{int((prev['count'] < 100).sum())}** of {len(prev)}",
        "",
        "### Diagnostic superclasses",
        sc.to_markdown(index=False),
        "",
        "### Top 15 statements",
        prev.head(15)[["code", "count", "prevalence_%", "description"]].to_markdown(index=False),
        "",
        "## Missingness (columns with any missing)",
        miss.to_markdown(index=False),
        "",
        "## Figures",
        "- `figures/code_prevalence.png` — all statements (log scale)",
        "- `figures/superclass_distribution.png`",
        "- `figures/demographics.png` — age + sex",
        "- `figures/labels_per_record.png`",
    ]
    (OUT / "summary.md").write_text("\n".join(lines) + "\n")
    print(f"EDA written to {OUT}")
    print(f"  records={demo['n_records']:,} patients={demo['n_patients']:,} "
          f"labels={len(L.build_label_space())}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
