#!/usr/bin/env python3
"""Train the baseline 1D-CNN detector on PTB-XL and export the per-label AUROC table.

    python -m src.detection.train                       # full 20-epoch baseline
    python -m src.detection.train --epochs 5            # shorter run
    python -m src.detection.train --smoke               # tiny end-to-end check (sample records)
    WANDB_MODE=offline python -m src.detection.train    # no cloud login needed

Multi-label setup: sigmoid head + BCEWithLogitsLoss with per-label ``pos_weight`` to
counter the class imbalance from Phase 1. Model selection is by macro-AUROC on the
validation fold. The final per-label AUROC table (the "before" number for later phases)
is written to ``docs/baseline/``.
"""

from __future__ import annotations

import argparse
import json
import time
from pathlib import Path

import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, TensorDataset

from src.config import CFG, ROOT
from src.data.labels import build_label_space, load_scp_statements
from src.detection.data_cache import build_split_cache
from src.detection.losses import build_loss
from src.detection.model import build_model, count_parameters
from src.eval.metrics import (
    expected_calibration_error,
    f1_scores,
    macro_auroc,
    per_label_auroc,
    tune_thresholds,
)

OUT_DIR = ROOT / "outputs"                      # checkpoints (gitignored)
BASELINE_DIR = ROOT / "docs" / "baseline"       # Phase 3 baseline table (committed)
COMPARE_DIR = ROOT / "docs" / "model_comparison"  # Phase 4 per-run tables + runs.jsonl

# Sample records present without the full download, for --smoke (see fetch_sample_records).
SMOKE_TRAIN_IDS = [1, 3, 22]
SMOKE_VAL_IDS = [8, 17, 30]


def pick_device(name: str) -> torch.device:
    if name != "auto":
        return torch.device(name)
    if torch.backends.mps.is_available():
        return torch.device("mps")
    if torch.cuda.is_available():
        return torch.device("cuda")
    return torch.device("cpu")


def set_seed(seed: int) -> None:
    np.random.seed(seed)
    torch.manual_seed(seed)


def pos_weight_from(Y: np.ndarray, cap: float) -> torch.Tensor:
    """Per-label BCE weight = (#neg / #pos), capped so ultra-rare labels don't explode.

    Degenerate columns (a label that is always or never positive in train) carry no
    imbalance signal, so they default to weight 1.0 rather than 0 or inf.
    """
    pos = Y.sum(axis=0)
    neg = len(Y) - pos
    with np.errstate(divide="ignore", invalid="ignore"):
        w = np.where((pos > 0) & (neg > 0), neg / np.maximum(pos, 1), 1.0)
    return torch.tensor(np.minimum(w, cap), dtype=torch.float32)


@torch.no_grad()
def predict(model: nn.Module, loader: DataLoader, device) -> tuple[np.ndarray, np.ndarray]:
    model.eval()
    probs, trues = [], []
    for xb, yb in loader:
        logits = model(xb.to(device))
        probs.append(torch.sigmoid(logits).cpu().numpy())
        trues.append(yb.numpy())
    return np.concatenate(trues), np.concatenate(probs)


def write_auroc_table(y_true, y_prob, label_space, train_support, out_dir: Path,
                      title: str = "Baseline detector", subtitle: str = "") -> dict:
    """Write the per-label AUROC table (CSV + markdown). Returns headline metrics."""
    import pandas as pd

    scp = load_scp_statements()
    aurocs = per_label_auroc(y_true, y_prob)
    rows = []
    for j, code in enumerate(label_space):
        rows.append({
            "code": code,
            "description": scp.loc[code, "description"] if code in scp.index else "",
            "train_support": int(train_support[j]),
            "val_support": int(y_true[:, j].sum()),
            "auroc": aurocs[j],
        })
    df = pd.DataFrame(rows).sort_values("auroc", ascending=False, na_position="last")
    out_dir.mkdir(parents=True, exist_ok=True)
    df.to_csv(out_dir / "val_per_label_auroc.csv", index=False)

    thr = tune_thresholds(y_true, y_prob)
    y_pred = (y_prob >= thr).astype(int)
    headline = {
        "macro_auroc": macro_auroc(y_true, y_prob),
        "ece": expected_calibration_error(y_true, y_prob),
        **f1_scores(y_true, y_pred),
        "n_val": int(len(y_true)),
        "labels_scored": int(df["auroc"].notna().sum()),
    }
    valid = df[df["auroc"].notna()]
    md = [
        f"# {title} — per-label AUROC (validation fold)",
        "",
        f"_{subtitle or 'Generated by `python -m src.detection.train`.'}_",
        "",
        f"- **Macro-AUROC: {headline['macro_auroc']:.4f}**  (over {headline['labels_scored']} "
        f"labels with both classes present in val)",
        f"- Macro-F1 {headline['macro_f1']:.4f} · Micro-F1 {headline['micro_f1']:.4f} "
        f"· ECE {headline['ece']:.4f} · n_val {headline['n_val']}",
        "",
        "> **Calibration caveat:** class-weighted training (`pos_weight` / focal) trades "
        "calibration for recall on rare labels, so raw probabilities run high and ECE is "
        "poor. AUROC (ranking) is the headline metric; probability calibration "
        "(temperature scaling) is follow-up work. F1 uses per-label thresholds tuned on "
        "this fold.",
        "",
        "### Best 10 labels", valid.head(10).to_markdown(index=False),
        "", "### Weakest 10 labels (scored)", valid.tail(10).to_markdown(index=False),
    ]
    (out_dir / "summary.md").write_text("\n".join(md) + "\n")
    (out_dir / "headline_metrics.json").write_text(json.dumps(headline, indent=2))
    return headline


def append_run_record(record: dict) -> None:
    """Append one experiment's summary to docs/model_comparison/runs.jsonl."""
    COMPARE_DIR.mkdir(parents=True, exist_ok=True)
    with (COMPARE_DIR / "runs.jsonl").open("a") as f:
        f.write(json.dumps(record) + "\n")


def eval_split(model, X, Y, device) -> dict:
    loader = DataLoader(TensorDataset(torch.from_numpy(X), torch.from_numpy(Y)), batch_size=256)
    y_true, y_prob = predict(model, loader, device)
    thr = tune_thresholds(y_true, y_prob)
    return {
        "macro_auroc": macro_auroc(y_true, y_prob),
        "ece": expected_calibration_error(y_true, y_prob),
        **f1_scores(y_true, (y_prob >= thr).astype(int)),
    }


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--model", default="cnn", choices=("cnn", "transformer"))
    ap.add_argument("--loss", default="bce", choices=("bce", "focal"))
    ap.add_argument("--focal-gamma", type=float, default=2.0)
    ap.add_argument("--run-name", default=None, help="defaults to <model>_<loss>")
    ap.add_argument("--epochs", type=int, default=20)
    ap.add_argument("--batch-size", type=int, default=128)
    ap.add_argument("--lr", type=float, default=1e-3)
    ap.add_argument("--weight-decay", type=float, default=1e-4)
    # CNN hparams
    ap.add_argument("--width", type=int, default=64)
    ap.add_argument("--blocks", type=int, default=2)
    # transformer hparams
    ap.add_argument("--d-model", type=int, default=128)
    ap.add_argument("--depth", type=int, default=3)
    ap.add_argument("--heads", type=int, default=4)
    ap.add_argument("--patch", type=int, default=25)
    ap.add_argument("--dropout", type=float, default=0.2)
    ap.add_argument("--pos-weight-cap", type=float, default=50.0)
    ap.add_argument("--sampling-rate", type=int, default=100, choices=(100, 500))
    ap.add_argument("--num-workers", type=int, default=4)
    ap.add_argument("--device", default="auto")
    ap.add_argument("--seed", type=int, default=42)
    ap.add_argument("--eval-test", action="store_true", help="also report test-fold metrics")
    ap.add_argument("--wandb-mode", default=CFG.wandb.mode, choices=("online", "offline", "disabled"))
    ap.add_argument("--smoke", action="store_true", help="tiny run on the sample records")
    args = ap.parse_args()

    if args.smoke:
        args.epochs, args.batch_size, args.num_workers = min(args.epochs, 2), 2, 0
        args.wandb_mode = "offline"
    run_name = args.run_name or f"{args.model}_{args.loss}"

    set_seed(args.seed)
    device = pick_device(args.device)
    print(f"run={run_name}  model={args.model}  loss={args.loss}  device={device}  epochs={args.epochs}")

    tr_ids = SMOKE_TRAIN_IDS if args.smoke else None
    va_ids = SMOKE_VAL_IDS if args.smoke else None
    print("loading/caching data...")
    Xtr, Ytr = build_split_cache("train", args.sampling_rate, num_workers=args.num_workers, ecg_ids=tr_ids)
    Xva, Yva = build_split_cache("val", args.sampling_rate, num_workers=args.num_workers, ecg_ids=va_ids)
    print(f"train {Xtr.shape}  val {Xva.shape}")

    train_loader = DataLoader(
        TensorDataset(torch.from_numpy(Xtr), torch.from_numpy(Ytr)),
        batch_size=args.batch_size, shuffle=True, drop_last=True,  # drop_last avoids BN on size-1 batch
    )
    val_loader = DataLoader(TensorDataset(torch.from_numpy(Xva), torch.from_numpy(Yva)), batch_size=256)

    label_space = build_label_space()
    model = build_model(
        args.model, width=args.width, blocks=args.blocks, dropout=args.dropout,
        d_model=args.d_model, depth=args.depth, heads=args.heads, patch=args.patch,
    ).to(device)
    n_params = count_parameters(model)
    print(f"model params: {n_params:,}")
    pos_weight = pos_weight_from(Ytr, args.pos_weight_cap).to(device)
    criterion = build_loss(args.loss, pos_weight=pos_weight, focal_gamma=args.focal_gamma)
    opt = torch.optim.AdamW(model.parameters(), lr=args.lr, weight_decay=args.weight_decay)
    sched = torch.optim.lr_scheduler.CosineAnnealingLR(opt, T_max=args.epochs)

    import wandb

    wandb.init(project=CFG.wandb.project, name=run_name, mode=args.wandb_mode,
               config={**vars(args), "params": n_params},
               tags=list(CFG.wandb.tags) + [args.model, args.loss])

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    best_path = OUT_DIR / f"{run_name}_best.pt"
    best_auroc, best_epoch, train_time = -1.0, 0, 0.0
    for epoch in range(1, args.epochs + 1):
        model.train()
        t0, running = time.time(), 0.0
        for xb, yb in train_loader:
            xb, yb = xb.to(device), yb.to(device)
            opt.zero_grad()
            loss = criterion(model(xb), yb)
            loss.backward()
            opt.step()
            running += loss.item() * len(xb)
        sched.step()
        train_time += time.time() - t0
        train_loss = running / max(1, len(train_loader.dataset))

        y_true, y_prob = predict(model, val_loader, device)
        m = {
            "macro_auroc": macro_auroc(y_true, y_prob),
            "ece": expected_calibration_error(y_true, y_prob),
            **f1_scores(y_true, (y_prob >= 0.5).astype(int)),
        }
        wandb.log({"epoch": epoch, "train_loss": train_loss, "lr": sched.get_last_lr()[0], **m})
        print(f"epoch {epoch:2d}/{args.epochs}  loss={train_loss:.4f}  "
              f"macroAUROC={m['macro_auroc']:.4f}  microF1={m['micro_f1']:.4f}  ({time.time()-t0:.1f}s)")

        if m["macro_auroc"] > best_auroc:
            best_auroc, best_epoch = m["macro_auroc"], epoch
            torch.save({"model": model.state_dict(), "args": vars(args), "epoch": epoch}, best_path)

    # Reload best; write the per-run table and log the run record.
    model.load_state_dict(torch.load(best_path)["model"])
    title = f"{args.model.upper()} + {args.loss}"
    subtitle = f"{args.model} / {args.loss} loss, {n_params:,} params, best epoch {best_epoch}"
    y_true, y_prob = predict(model, val_loader, device)
    val_headline = write_auroc_table(y_true, y_prob, label_space, Ytr.sum(axis=0),
                                     COMPARE_DIR / run_name, title=title, subtitle=subtitle)

    record = {
        "run_name": run_name, "model": args.model, "loss": args.loss,
        "params": n_params, "epochs": args.epochs, "best_epoch": best_epoch,
        "lr": args.lr, "dropout": args.dropout, "pos_weight_cap": args.pos_weight_cap,
        "focal_gamma": args.focal_gamma if args.loss == "focal" else None,
        "train_time_s": round(train_time, 1),
        "val_macro_auroc": val_headline["macro_auroc"], "val_macro_f1": val_headline["macro_f1"],
        "val_micro_f1": val_headline["micro_f1"], "val_ece": val_headline["ece"],
    }
    print(f"\nBEST val macro-AUROC {best_auroc:.4f} (epoch {best_epoch}, {train_time:.0f}s train)")

    if args.eval_test:
        Xte, Yte = build_split_cache("test", args.sampling_rate, num_workers=args.num_workers)
        test_m = eval_split(model, Xte, Yte, device)
        record.update({"test_macro_auroc": test_m["macro_auroc"], "test_macro_f1": test_m["macro_f1"],
                       "test_micro_f1": test_m["micro_f1"]})
        print(f"TEST macro-AUROC {test_m['macro_auroc']:.4f}  macro-F1 {test_m['macro_f1']:.4f}")

    append_run_record(record)
    print(f"per-label table -> {COMPARE_DIR / run_name}  |  record -> runs.jsonl")
    if wandb.run is not None:
        wandb.summary.update({k: v for k, v in record.items() if isinstance(v, (int, float))})
        wandb.finish()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
